export const objectMapping = {
    "rendersettings": "rendersettings",
    "lore": "lore",
    "light": "light",
    "Street.green": "Street.green",
    "barrier": "barrier",
    "infinifruit": "infinifruit",
    "index": "index",
    "silkworm": "silkworm",
    "ramp": "ramp",
    "originTablet": "originTablet",
    "turret": "turret",
    "lisk": "lisk",
    "dragon-mount": "dragon-mount",
    "bomb": "bomb",
    "hovercraft": "hovercraft",
    "Witchhat": "Witch hat",
    "dreadnought": "dreadnought",
    "treehouse": "treehouse",
    "scissors": "scissors",
    "mirror": "mirror",
    "fruit": "fruit",
    "potion": "potion",
    "flower": "flower",
    "bow": "bow",
    "silsword": "silsword",
    "jun_engineer_v1_vian": "jun_engineer_v1_vian",
    "scillia_drophunter_v15_vian": "scillia_drophunter_v15_vian",
    "pistol": "pistol",
    "drake_hacker_v3_vian": "drake_hacker_v3_vian",
    "hya_influencer_v2_vian": "hya_influencer_v2_vian",
    "Drake": "drake_hacker_v3_vian",
    "Scillia": "scillia_drophunter_v15_vian",
    "Hyacinth": "hya_influencer_v2_vian",
    "Juniper": "jun_engineer_v1_vian"
 }